### ISSUE TITLE
Handling of disconnected and reconnected device

### ISSUE THREAD

**Issue by tomaae** [Limych/ha-jq300#1]
**Version of the custom_component**

Version not found in __init__.py, commit 45597c6

**Configuration**
```yaml
Contains only login and password.
```

**Describe the bug**
1. When device is unreachable, entities wont go to unavailable state.
2. When device is unreachable, it will spam the log with error message.
3. After device is reachable again, error message continues and entities are not updated.

**To Reproduce**
Unplug the device from power and wait

**Expected behavior**
1. All entities should change to unavailable state.
2. Error should appear only once in error log and should not repeat until device responds again.
3. After device is available again, it should reconnect.

**Debug log**

```text
2020-04-19 23:46:55 ERROR (SyncWorker_1) [custom_components.jq300] Sorry.. Something went wrong...
```

**Comment by Limych** [comment]
Fixed in last version of integration.
