### ISSUE TITLE
Component error: jq300 - cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### ISSUE THREAD

**Issue by jjanderson** [Limych/ha-jq300#11]
**Versions**

* Version of the Home Assistant:
* Version of the custom component:

**Configuration**
```yaml

Add your configs here.

```

**Describe the bug**

**To Reproduce**

If applicable, describe the steps to reproduce the behavior:
1. Go to 'configuration'
2. Click on 'check config'

**Expected behavior**

**Screenshots**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment]
Issues not containing the minimum requirements will be closed:

- Issues without a description (using the header is not good enough) will be closed.
- Issues without debug logging will be closed.
- Issues without configuration will be closed
