### ISSUE TITLE
Setup failed for jq300: Unable to import component: No module named 'paho'

### ISSUE THREAD

**Issue by S1m0n3** [Limych/ha-jq300#14]
Hello, with the latest version of this component (0.7.17) I receive always this error and can't use anymore

Setup failed for jq300: Unable to import component: No module named 'paho'

I've also tried to install manually paho-mqtt but receive an error!

Thanks you so much for your support!

**Comment by Limych** [comment]
Please note that most programmers are not mind reading skills. If you say that you get an error while trying to manually install the module, please cite the entire error message. Perhaps then the programmer can help you ...

And it will be even better if, when creating an issue, you use the template that is provided here initially - so the programmer will receive all the information necessary for work without unnecessary questions and expectations. And everyone will be happy... ;)
