### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by AkinfievS** [Limych/ha-jq300#15]
Доброго времени суток.

Я в теме новичок. Помогите!

Logger: homeassistant.setup
Source: setup.py:138
First occurred: 9 декабря 2020 г., 15:39:27 (3 occurrences)
Last logged: 9 декабря 2020 г., 15:39:28

Setup failed for iaquk: Invalid config.
Setup failed for devices: Integration not found.
Setup failed for jq300: Integration not found.

-----------------

Logger: homeassistant.config
Source: config.py:415
First occurred: 9 декабря 2020 г., 15:39:27 (1 occurrences)
Last logged: 9 декабря 2020 г., 15:39:27

Invalid config for [iaquk]: invalid slug Kitchen (try kitchen) for dictionary value @ data['iaquk']. Got OrderedDict([('Kitchen', OrderedDict([('sources', OrderedDict([('humidity', 'sensor.kitchen_humidity'), ('co2', 'sensor.kitchen_eco2'), ('tvoc', 'sensor.kitchen_tvoc'), ('hcho', 'sensor.kitchen_hcho'), ('pm', 'sensor.kitchen_pm25')]))]))]). (See /config/configuration.yaml, line 19). Please check the docs at https://github.com/Limych/ha-iaquk

**Comment by Limych** [comment]
Пожалуйста, оформите багрепорт в соответствии с предоставленным изначально шаблоном. Вот он, если что: https://github.com/Limych/ha-jq300/raw/master/.github/ISSUE_TEMPLATE/bug_report.md
