### ISSUE TITLE
JQ200 and JQ300 not always identical

### ISSUE THREAD

**Issue by fabicodes** [Limych/ha-jq300#18]
The README.md states:
> **Note:**\
> It was discovered that there is [no difference between the JQ-200 and JQ-300](https://community.home-assistant.io/t/jq-300-200-100-indoor-air-quality-meter/189098/42) models. Although the JQ-200 does not show PM2.5 sensor data in the official app, in fact this data is collected and transmitted from the cloud. Our component sees and displays them correctly. So you have the opportunity to save some money if you wish when purchasing.

This is not always the case. I just received a JQ200 and it was missing the Particle Sensor Component inside. The main PCB seems to be identical to the JQ300 and even the App displays an JQ300 Model, but there is no way of reading out PM2.5 data if there is no sensor inside. There is however the connector for the sensor

**Comment by fabicodes** [comment]
Just tested the integration, it shows a PM2.5 Value of 35 - not sure yet whether this will be a constant value.
According to the picture in this #[issue](https://github.com/xoseperez/espurna/issues/1644#issuecomment-753093763) it seems the PM2.5 Sensor is connected via an ADC. So this will probably stay constant or fluctuate with the input voltage or something else

**Comment by eMadman** [comment]
I received my JQ200 recently.  I took it apart to see the insides - there is no hardware PM2.5 sensor in the body.  This PCB is the only thing that was inside of mine:
![image](https://user-images.githubusercontent.com/24726844/109325732-46fbe080-7824-11eb-8845-6e0b9248f483.png)

From this github post: https://github.com/xoseperez/espurna/issues/1644  it appears to be a SHARP PM2.5 sensor connected to the board.  I suspect not all models of the JQ200 shipped with it.  On its own, the PM2.5 sensor is about $10 on Aliexpress so I can see why it wouldn't be on the cheaper models.  The value I'm seeing in HA is fixed at 35 and hasn't really fluctuated above that in 24 hours, although, I've seen values below that.  This is likely either a calculated value or dummy value coming through the API.  Regardless, it's not usable data. Still very neat to see this.  It might be worth picking up a pm2.5 sensor and dropping it in to see if the board will simply recognize it and start reporting on it.  I can't imagine the firmware is different between the JQ200 and 300

**Comment by Limych** [comment]
Thank you, guys.
