### ISSUE TITLE
Make polling interval adjustable 

### ISSUE THREAD

**Issue by remyderuysscher** [Limych/ha-jq300#6]
Frequent access to the cloud (MQTT) causes a ban. My IP address was blacklisted and my account was labeled as "Bad account, please try again in 1 hr."

I have a dynamic IP address and was able to get a different IP address. When I stopped the integration for a few hours the app was working again.

Please set polling interval to 30 min.

**Comment by wiebeww** [comment]
I have the same issue.
Is it possible to change this?

**Comment by NicoSomerwil** [comment]
same issue for me

**Comment by Limych** [comment]
Yes, unfortunately, the Chinese have switched on some kind of protection that blocks the IP addresses where this custom component is used.

So far I see only one solution: 

# Solution

The component has been changed to request data less often. You need to update the component code to the latest version, and THEN change the external IP address of your Home Assistant - usually it’s enough just to restart the router, which is responsible for accessing the Internet.

It is not yet possible to verify the reliable performance of this method, so I will say this: I hope this helps to solve this problem forever.
