### ISSUE TITLE
Integration error, it can't connect to the chinese API. Any hint or help? Thanks!

### ISSUE THREAD

**Issue by wokawoka** [Limych/ha-jq300#7]
**Version of the custom_component**
actaul version downloaded today from github

**Configuration**
(copied just the part involved in this component)
q300:
  username: my email
  password: my password
  devices: jq300

**Describe the bug**
Integration error, it can't connect to the chinese API. Any hint or help? Thanks!

**Debug log**
    Error! HTTPSConnectionPool(host='www.youpinyuntai.com', port=31447): Read timed out. (read timeout=7)

Log Details (ERROR)
Logger: custom_components.jq300
Source: custom_components/jq300/__init__.py:366
Integration: jq300 (documentation)
First occurred: 2:54:30 PM (1 occurrences)
Last logged: 2:54:30 PM 

Error! HTTPConnectionPool(host='www.youpinyuntai.com', port=32086): Max retries exceeded with url: /ypyt-api/api/app/loginByEmail?uid=-1000&safeToken=anonymous&chr=clt&email=REMOVED&password=REMOVED&os=2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xb03d06d0>, 'Connection to www.youpinyuntai.com timed out. (connect timeout=7)'))

**Comment by Limych** [comment]
Same as #6

**Comment by wokawoka** [comment]
Actually I did never receive any error in the app; if I disable the integration and login again from the mobile everything keeps working therefore I'm not really sure that the problem is that my IP gets banned (it doesn't look like so).
Any other idea, by chance? Thank you
