### ISSUE TITLE
Updates need?

### ISSUE THREAD

**Issue by kdutton1964** [Limych/ha-jq300#84]
When starting this in the log. Thank you for all your work

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:580 
First occurred: 8:31:46 PM (7 occurrences) 
Last logged: 8:31:47 PM

Entity sensor.kitchen_aqi_humidity (<class 'custom_components.jq300.sensor.Jq300Sensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.kitchen_aqi_pm25 (<class 'custom_components.jq300.sensor.Jq300Sensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.kitchen_aqi_hcho (<class 'custom_components.jq300.sensor.Jq300Sensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.kitchen_aqi_tvoc (<class 'custom_components.jq300.sensor.Jq300Sensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.kitchen_aqi_eco2 (<class 'custom_components.jq300.sensor.Jq300Sensor'>) implements device_state_attributes. Please report it to the custom component author.

**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment]
Thanks :heart:
